package com.in28minutes.exceptionhandling;

import java.util.Scanner;

public class FinallyRunner {

	public static void main(String[] args) {
		
		Scanner scanner = null;

		try {
			scanner = new Scanner(System.in);
			int[] numbers = { 12, 3, 4, 5 };

			int number = numbers[0];

			System.out.println(" "+number);

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			System.out.println("ndsihon mafa dswoerver dsefnafga dajssjkjisbuk");
			if (scanner != null) {
				scanner.close();
			}
		}
		
		System.out.println("Just before closing out main");//fdsasdfdsasdfdsasdfdsasfddfdsadsfdsasdfdsasdfdfdsasdfdsasffdsfadfadsasdfdsasdfdsafsdfdasfdsfadsfafdasasdfdsfdsafdsasafsddfdsasdfdsfadsafdsfadsfdsasdfgdsfgadssdadsadsadsafadfadsdasfdsafsdsfdfddfsdaaasdfgsfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdsadsfdsfaDSFADSFADSFDFDASDFGDSADSFDASFDFADSDAFSDAFDSAFDSFADSFDASDFADFSFADSDFSADFFDASDFSAFDSADFDFSASDFSFDADFSADFSAFDSAFDSDFAFDASFDSAFDFDSAFDSFAFDSDFASDFADS ASA SA SA SDFASDFADS SDAFDSAFDSFADSFADSFASASDAFSASDFGDASFDFSDDDFSSSSFADAFSDASSADDSASDSDSASDDSADSDADSASDSASASFSFASFASFSFSASAFSSAAFDFDSASDFDSASDFDSASDFDSASFDSASDFDSAFDSSADFFFSAFDFFSDDFSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFDSAFSDFGADSFGADSFADSFADSFADSFSDAFSFDSADFSADFDAFFDASFDASDFSAFDSADFSASDFASDFGADSAGFDSFGADSGFADSGFADSFDSFDAFASDFSDFFDFSDSFFDSFSDAASASFDFSADFSADASDFSDAFASDFASDFASFFDSASDFDSFASDAFSDAFSDfdsasdfdsasdfdsasdfdsasfddfdsadsfdsasdfdsasdfdfdsasdfdsasffdsfadfadsasdfdsasdfdsafsdfdasfdsfadsfafdasasdfdsfdsafdsasafsddfdsasdfdsfadsafdsfadsfdsasdfgdsfgadssdadsadsadsafadfadsdasfdsafsdsfdfddfsdaaasdfgsfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdsadsfdsfaDSFADSFADSFDFDASDFGDSADSFDASFDFADSDAFSDAFDSAFDSFADSFDASDFADFSFADSDFSADFFDASDFSAFDSADFDFSASDFSFDADFSADFSAFDSAFDSDFAFDASFDSAFDFDSAFDSFAFDSDFASDFADSfdsasdfdsasdfdsasdfdsasfddfdsadsfdsasdfdsasdfdfdsasdfdsasffdsfadfadsasdfdsasdfdsafsdfdasfdsfadsfafdasasdfdsfdsafdsasafsddfdsasdfdsfadsafdsfadsfdsasdfgdsfgadssdadsadsadsafadfadsdasfdsafsdsfdfddfsdaaasdfgsfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdsadsfdsfaDSFADSFADSFDFDASDFGDSADSFDASFDFADSDAFSDAFDSAFDSFADSFDASDFADFSFADSDFSADFFDASDFSAFDSADFDFSASDFSFDADFSADFSAFDSAFDSDFAFDASFDSAFDFDSAFDSFAFDSDFASDFADSASDFAFSDfaSDFASDFS
	}

}
